/*if(c1 == 1 && c2 ==1 && c3==1){priority = 5;return priority;}
    else if(c1 == 1 && c2 ==1 && c3==2){priority = 5;return priority;}
    else if(c1 == 1 && c2 ==1 && c3==3){priority = 5;return priority;}
    else if(c1 == 2 && c2 ==1 && c3==1){priority = 5;return priority;}
    else if(c1 == 2 && c2 ==1 && c3==2){priority = 5;return priority;}
    else if(c1 == 2 && c2 ==1 && c3==3){priority = 5;return priority;}
    else if(c1 == 3 && c2 ==1 && c3==1){priority = 5;return priority;}
    else if(c1 == 3 && c2 ==1 && c3==2){priority = 5;return priority;}
    else if(c1 == 3 && c2 ==1 && c3==3){priority = 5;return priority;}
    else if(c1 == 4 && c2 ==1 && c3==1){priority = 5;return priority;}
    else if(c1 == 4 && c2 ==1 && c3==2){priority = 5;return priority;}
    else if(c1 == 4 && c2 ==1 && c3==3){priority = 5;return priority;}
    else if(c1 == 1 && c2 ==2 && c3==1){priority = 5;return priority;}
    else if(c1 == 1 && c2 ==2 && c3==2){priority = 5;return priority;}
    else if(c1 == 1 && c2 ==2 && c3==3){priority = 5;return priority;}
    else if(c1 == 2 && c2 ==2 && c3==1){priority = 5;return priority;}
    else if(c1 == 2 && c2 ==2 && c3==2){priority = 5;return priority;}
    else if(c1 == 2 && c2 ==2 && c3==3){priority = 5;return priority;}
    else if(c1 == 3 && c2 ==2 && c3==1){priority = 4;return priority;}
    else if(c1 == 3 && c2 ==2 && c3==2){priority = 4;return priority;}
    else if(c1 == 3 && c2 ==2 && c3==3){priority = 4;return priority;}
    else if(c1 == 4 && c2 ==2 && c3==1){priority = 5;return priority;}
    else if(c1 == 4 && c2 ==2 && c3==2){priority = 5;return priority;}
    else if(c1 == 4 && c2 ==2 && c3==3){priority = 5;return priority;}
    else if(c1 == 1 && c2 ==3 && c3==1){priority = 5;return priority;}
    else if(c1 == 1 && c2 ==3 && c3==2){priority = 5;return priority;}
    else if(c1 == 1 && c2 ==3 && c3==3){priority = 5;return priority;}
    else if(c1 == 2 && c2 ==3 && c3==1){priority = 5;return priority;}
    else if(c1 == 2 && c2 ==3 && c3==2){priority = 5;return priority;}
    else if(c1 == 2 && c2 ==3 && c3==3){priority = 5;return priority;}
    else if(c1 == 3 && c2 ==3 && c3==1){priority = 5;return priority;}
    else if(c1 == 3 && c2 ==3 && c3==2){priority = 5;return priority;}
    else if(c1 == 3 && c2 ==3 && c3==3){priority = 5;return priority;}
    else if(c1 == 4 && c2 ==3 && c3==1){priority = 5;return priority;}
    else if(c1 == 4 && c2 ==3 && c3==2){priority = 5;return priority;}
    else if(c1 == 4 && c2 ==3 && c3==3){priority = 5;return priority;}
    else if(c1 == 1 && c2 ==4 && c3==1){priority = 5;return priority;}
    else if(c1 == 1 && c2 ==4 && c3==2){priority = 5;return priority;}
    else if(c1 == 1 && c2 ==4 && c3==3){priority = 5;return priority;}
    else if(c1 == 2 && c2 ==4 && c3==1){priority = 5;return priority;}
    else if(c1 == 2 && c2 ==4 && c3==2){priority = 5;return priority;}
    else if(c1 == 2 && c2 ==4 && c3==3){priority = 5;return priority;}
    else if(c1 == 3 && c2 ==4 && c3==1){priority = 5;return priority;}
    else if(c1 == 3 && c2 ==4 && c3==2){priority = 5;return priority;}
    else if(c1 == 3 && c2 ==4 && c3==3){priority = 5;return priority;}
    else if(c1 == 4 && c2 ==4 && c3==1){priority = 5;return priority;}
    else if(c1 == 4 && c2 ==4 && c3==2){priority = 5;return priority;}
    else if(c1 == 4 && c2 ==4 && c3==3){priority = 5;return priority;}
    else if(c1 == 1 && c2 ==5 && c3==1){priority = 5;return priority;}
    else if(c1 == 1 && c2 ==5 && c3==2){priority = 5;return priority;}
    else if(c1 == 1 && c2 ==5 && c3==3){priority = 5;return priority;}
    else if(c1 == 2 && c2 ==5 && c3==1){priority = 5;return priority;}
    else if(c1 == 2 && c2 ==5 && c3==2){priority = 5;return priority;}
    else if(c1 == 2 && c2 ==5 && c3==3){priority = 5;return priority;}
    else if(c1 == 3 && c2 ==5 && c3==1){priority = 5;return priority;}
    else if(c1 == 3 && c2 ==5 && c3==2){priority = 5;return priority;}
    else if(c1 == 3 && c2 ==5 && c3==3){priority = 5;return priority;}
    else if(c1 == 4 && c2 ==5 && c3==1){priority = 5;return priority;}
    else if(c1 == 4 && c2 ==5 && c3==2){priority = 5;return priority;}
    else if(c1 == 4 && c2 ==5 && c3==3){priority = 5;return priority;}*/